"""
Conversation engine for round-based chat between multiple agents.
"""

from typing import Any, Optional

from .models import AgentConfig, Conversation, Message
from .ollama_client import OllamaClient


class ConversationEngine:
    """Engine for running round-based conversations between agents."""

    def __init__(
        self,
        conversation: Conversation,
        agents: list[AgentConfig],
        client: OllamaClient | None = None,
    ):
        """
        Initialize the conversation engine.

        Args:
            conversation: The conversation object to manage
            agents: List of agent configurations
            client: OllamaClient instance (creates default if None)
        """
        self.conversation = conversation
        self.agents = agents
        self.client = client or OllamaClient()

    async def run_round(self, current_agent: AgentConfig | None = None) -> Message:
        """
        Execute a single round where one agent speaks.

        Args:
            current_agent: The agent to speak (uses first agent if None)

        Returns:
            The message generated by the agent

        Raises:
            ValueError: If no agents are configured
        """
        if not self.agents:
            raise ValueError("No agents configured")

        agent = current_agent or self.agents[0]

        # Build messages for chat API
        messages = self._build_chat_messages(agent)

        # Build options - only add num_predict if max_tokens is set
        options: dict[str, Any] = {"temperature": agent.temperature}
        if agent.max_tokens is not None:
            options["num_predict"] = agent.max_tokens

        # Get response from Ollama using chat API
        response = await self.client.chat(
            messages=messages,
            model=agent.model,
            options=options,
        )

        # Create and store message
        content = response.strip()
        if not content:
            content = f"[No response from {agent.name} - model returned empty]"
        message = Message(
            role="assistant",
            content=content,
            agent_id=agent.name,
        )

        self.conversation.messages.append(message)
        if agent.name not in self.conversation.participants:
            self.conversation.participants.append(agent.name)

        return message

    async def run_conversation(
        self,
        num_rounds: int = 3,
        topic: str | None = None,
    ) -> Conversation:
        """
        Run a complete conversation with multiple rounds.

        Args:
            num_rounds: Number of rounds (each agent speaks once per round)
            topic: Optional topic to set for the conversation

        Returns:
            The updated conversation with all messages
        """
        if topic:
            self.conversation.topic = topic

        # Add topic as initial system message if provided
        if topic and not self.conversation.messages:
            initial_message = Message(
                role="system",
                content=f"The topic of this conversation is: {topic}",
            )
            self.conversation.messages.append(initial_message)

        for round_num in range(num_rounds):
            for agent in self.agents:
                await self.run_round(current_agent=agent)

        return self.conversation

    def _build_chat_messages(self, agent: AgentConfig) -> list[Message]:
        """
        Build messages for chat API - agent should respond to the conversation.
        """
        messages = []
        
        # System message with topic and agent identity
        topic_str = f"Das Thema ist: {self.conversation.topic}. " if self.conversation.topic else ""
        system_msg = f"{topic_str}Du bist {agent.name}, {agent.role}. {agent.instructions}. Antworte auf das Gesagte - reagiere direkt auf die anderen."
        messages.append(Message(role="user", content=system_msg))
        
        # Add conversation history (last messages from others)
        relevant_messages = [m for m in self.conversation.messages if m.role != "system"][-5:]
        for msg in relevant_messages:
            # Map agent messages to user/assistant roles
            if msg.agent_id == agent.name:
                role = "assistant"
            else:
                role = "user"
            messages.append(Message(role=role, content=f"{msg.agent_id}: {msg.content}"))
        
        # Final prompt
        if not relevant_messages:
            messages.append(Message(role="user", content=f"Stell dich vor als {agent.name} und sag etwas zum Thema."))
        else:
            messages.append(Message(role="user", content=f"Was sagst du dazu, {agent.name}?"))
        
        return messages

    def _build_context(self, agent: AgentConfig) -> str:
        """
        Build context prompt for an agent based on conversation history.

        Args:
            agent: The agent requesting context

        Returns:
            A formatted context string for the agent
        """
        context_parts = []

        # Add role and instructions
        context_parts.append(f"You are {agent.name}, {agent.role}.")
        context_parts.append(f"Your instructions: {agent.instructions}")
        context_parts.append("")

        # Add conversation history
        if self.conversation.messages:
            context_parts.append("Conversation so far:")
            for msg in self.conversation.messages:
                # Skip system messages in context
                if msg.role == "system":
                    continue

                sender = msg.agent_id or msg.role
                context_parts.append(f"{sender}: {msg.content}")

        context_parts.append("")
        context_parts.append(f"Now it's your turn, {agent.name}. Respond naturally.")

        return "\n".join(context_parts)

    async def close(self) -> None:
        """Close the underlying Ollama client."""
        await self.client.close()

    async def __aenter__(self) -> "ConversationEngine":
        """Async context manager entry."""
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None:
        """Async context manager exit."""
        await self.close()
